# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bvsPGcpp <- function(iterations, thin, prior, DP_beta, DP_kappa, Y, W, subject, subject_dems, Ustar, Ustar_dems, Xbar, Z, random_avail, fixed_avail, beta, v, xi, mu, t2, cluster, cluster_count, cluster_beta, vartheta, K, lambda, Gamma, zeta, cluster_K, cluster_count_K, cluster_kappa, sA, V_gamma, gamma_0, m_star, v_star, m_0, v_0, a, b, a_K, b_K, a_0, b_0, a_vartheta, b_vartheta, a_sA, b_sA) {
    .Call(`_PGBVS_bvsPGcpp`, iterations, thin, prior, DP_beta, DP_kappa, Y, W, subject, subject_dems, Ustar, Ustar_dems, Xbar, Z, random_avail, fixed_avail, beta, v, xi, mu, t2, cluster, cluster_count, cluster_beta, vartheta, K, lambda, Gamma, zeta, cluster_K, cluster_count_K, cluster_kappa, sA, V_gamma, gamma_0, m_star, v_star, m_0, v_0, a, b, a_K, b_K, a_0, b_0, a_vartheta, b_vartheta, a_sA, b_sA)
}

